#!/bin/sh
output=$(acpi -b)
regex="Battery 0: ([a-zA-Z]+), ([0-9]+)%, ([0-9]{2}:[0-9]{2})*"

if [[ $output =~ $regex ]]; then
  status="${BASH_REMATCH[1]}"
  percent="${BASH_REMATCH[2]}"
  remaining="${BASH_REMATCH[3]}"
fi

if [[ "$status" = 'Charging' ]]; then
  icon=''
elif [[ "$status" = 'Discharging' ]]; then
  if [ "$percent" -lt 20 ]; then
    icon=''
  elif [ "$percent" -lt 40 ]; then
    icon=''
  elif [ "$percent" -lt 60 ]; then
    icon=''
  elif [ "$percent" -lt 80 ]; then
    icon=''
  else
    icon=''
  fi
fi

printf "%s  % 3d%% (%s)\n" $icon $percent $remaining
echo

if [[ "$status" = 'Discharging' ]]; then
  if [ "$percent" -lt 30 ]; then
    echo "#BE5046"
  elif [ "$percent" -lt 60 ]; then
    echo "#D19A66"
  else
    echo "#98C379"
  fi
fi

if [ "$percent" -lt 20 ]; then
  exit 33
fi
