#!/bin/sh

output=$(mpstat 1 1)
regex="([0-9]+),([0-9]+)$"
icon=''

colors=($(xrdb -query | awk '/color(1|3|7):/{print $2}'))
danger=${colors[0]}
warning=${colors[1]}
color=${colors[2]}

if [[ $output =~ $regex ]]; then
  idle="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  usage=$(echo "100 $idle" | awk '{printf "%d", $1 - $2}')
fi

if [ "$usage" -ge 80 ]; then
  color=$danger
elif [ "$usage" -ge 50 ]; then
  color=$warning
fi

printf '<span color="%s">%s</span>  %02d%%\n' $color $icon $usage
