#!/bin/sh

output=$(mpstat 1 1)
regex="([0-9]+),([0-9]+)$"

if [[ $output =~ $regex ]]; then
  idle="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  usage=$(echo "100 $idle" | awk '{printf "%d", $1 - $2}')
fi

result=$(printf "% 3d" "$usage")

echo "$result%"
echo "$result%"

if [ "$usage" -ge 80 ]; then
  echo "#FF0000"
elif [ "$usage" -ge 50 ]; then
  echo "#FFFC00"
fi
