#!/bin/sh

colors=($(xrdb -query | sort | awk '/\.color(6|8):/{print $2}'))
spinning=${colors[0]}
still=${colors[1]}
color=$still
icon=''

rpm_value=$(sensors dell_smm-virtual-0 -Au | awk ' /.fan1_input/ {printf("%d\n", $2)}')

if [[ $rpm_value -gt 0 ]]; then
  color=$spinning
fi

printf '%s  %04d\n\n%s\n' $icon $rpm_value $color
